package com.codechecker.report;

import com.codechecker.model.*;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.nio.file.*;
import java.time.LocalDate;

/**
 * Generates a standalone HTML report for the scan results.
 */
@Service
public class HtmlReportGenerator {

    public String generateReport(ScanResult result, Path outputDir) throws IOException {
        StringBuilder html = new StringBuilder();
        html.append("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n");
        html.append("<meta charset=\"UTF-8\">\n");
        html.append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
        html.append("<title>CodeChecker Report — ").append(result.getScanId()).append("</title>\n");
        html.append("<style>\n");
        html.append(getReportCss());
        html.append("</style>\n</head>\n<body>\n");

        // Header
        html.append("<div class=\"header\">\n");
        html.append("<h1>CodeChecker Health Report</h1>\n");
        html.append("<p>Scan ID: ").append(result.getScanId()).append(" | Date: ").append(LocalDate.now()).append("</p>\n");
        html.append("</div>\n");

        // Health Score
        String scoreClass = result.getHealthScore() >= 75 ? "score-good"
                : result.getHealthScore() >= 50 ? "score-warn" : "score-bad";
        html.append("<div class=\"score-card ").append(scoreClass).append("\">\n");
        html.append("<h2>").append(result.getHealthScore()).append(" / 100</h2>\n");
        html.append("<p>Grade: ").append(result.getGrade()).append("</p>\n");
        html.append("<p>").append(result.getReleaseDecision()).append("</p>\n");
        html.append("</div>\n");

        // Summary cards
        html.append("<div class=\"cards\">\n");
        html.append(card("Endpoints", String.valueOf(result.getTotalEndpoints())));
        html.append(card("Issues", String.valueOf(result.getAllIssues() != null ? result.getAllIssues().size() : 0)));
        html.append(card("Critical", String.valueOf(result.getCriticalCount())));
        html.append(card("Diagrams", String.valueOf(result.getDiagramsGenerated())));
        html.append(card("Files", String.valueOf(result.getTotalFiles())));
        html.append("</div>\n");

        // API Performance Table
        if (result.getAllEndpoints() != null && !result.getAllEndpoints().isEmpty()) {
            html.append("<h2>API Performance</h2>\n");
            html.append("<table>\n<tr><th>Endpoint</th><th>Method</th><th>Rating</th><th>p50</th><th>p95</th><th>Issues</th></tr>\n");
            for (EndpointInfo ep : result.getAllEndpoints()) {
                String ratingClass = "rating-" + (ep.getPerformanceRating() != null ? ep.getPerformanceRating().toLowerCase() : "unknown");
                html.append("<tr><td>").append(ep.getPath())
                        .append("</td><td>").append(ep.getHttpMethod())
                        .append("</td><td class=\"").append(ratingClass).append("\">").append(ep.getPerformanceRating())
                        .append("</td><td>~").append(ep.getEstimatedP50Ms()).append("ms")
                        .append("</td><td>~").append(ep.getEstimatedP95Ms()).append("ms")
                        .append("</td><td>").append(ep.getIssues().size())
                        .append("</td></tr>\n");
            }
            html.append("</table>\n");
        }

        // Issues
        if (result.getAllIssues() != null && !result.getAllIssues().isEmpty()) {
            html.append("<h2>Issues (").append(result.getAllIssues().size()).append(")</h2>\n");
            for (IssueInfo issue : result.getAllIssues()) {
                String sevClass = "sev-" + issue.getSeverity().toLowerCase();
                html.append("<div class=\"issue ").append(sevClass).append("\">\n");
                html.append("<h3>").append(issue.getRuleId()).append(" — ").append(issue.getTitle()).append("</h3>\n");
                html.append("<p><strong>Severity:</strong> ").append(issue.getSeverity()).append("</p>\n");
                if (issue.getDescription() != null) {
                    html.append("<p>").append(issue.getDescription()).append("</p>\n");
                }
                if (issue.getBeforeCode() != null) {
                    html.append("<p><strong>Before:</strong></p>\n<pre>").append(escapeHtml(issue.getBeforeCode())).append("</pre>\n");
                }
                if (issue.getAfterCode() != null) {
                    html.append("<p><strong>Suggested After:</strong></p>\n<pre class=\"fix\">").append(escapeHtml(issue.getAfterCode())).append("</pre>\n");
                }
                html.append("</div>\n");
            }
        }

        html.append("<footer><p>Generated by CodeChecker v1.0.0</p></footer>\n");
        html.append("</body>\n</html>\n");

        Path file = outputDir.resolve("codechecker-report.html");
        Files.writeString(file, html.toString());
        return file.toString();
    }

    private String card(String label, String value) {
        return "<div class=\"card\"><h3>" + value + "</h3><p>" + label + "</p></div>\n";
    }

    private String escapeHtml(String text) {
        if (text == null) return "";
        return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;");
    }

    private String getReportCss() {
        return """
            * { margin: 0; padding: 0; box-sizing: border-box; }
            body { font-family: 'Segoe UI', system-ui, sans-serif; background: #0f1117; color: #e1e4e8; padding: 2rem; }
            .header { text-align: center; margin-bottom: 2rem; }
            .header h1 { font-size: 2rem; background: linear-gradient(135deg, #667eea, #764ba2); -webkit-background-clip: text; -webkit-text-fill-color: transparent; }
            .score-card { text-align: center; padding: 2rem; border-radius: 16px; margin: 1.5rem auto; max-width: 400px; }
            .score-good { background: linear-gradient(135deg, #1a3a2a, #0d4023); border: 1px solid #27ae6080; }
            .score-warn { background: linear-gradient(135deg, #3a2a1a, #402d0d); border: 1px solid #f39c1280; }
            .score-bad { background: linear-gradient(135deg, #3a1a1a, #400d0d); border: 1px solid #e74c3c80; }
            .score-card h2 { font-size: 3rem; }
            .cards { display: flex; gap: 1rem; flex-wrap: wrap; justify-content: center; margin: 2rem 0; }
            .card { background: #161b22; border: 1px solid #30363d; border-radius: 12px; padding: 1.5rem; text-align: center; min-width: 120px; }
            .card h3 { font-size: 2rem; color: #58a6ff; }
            table { width: 100%; border-collapse: collapse; margin: 1rem 0; }
            th, td { padding: 0.75rem 1rem; text-align: left; border-bottom: 1px solid #30363d; }
            th { background: #161b22; color: #8b949e; font-weight: 600; }
            .rating-fast { color: #3fb950; }
            .rating-moderate { color: #d29922; }
            .rating-slow { color: #f85149; }
            .rating-critical { color: #ff0000; font-weight: bold; }
            .issue { background: #161b22; border: 1px solid #30363d; border-radius: 12px; padding: 1.5rem; margin: 1rem 0; }
            .issue h3 { color: #58a6ff; margin-bottom: 0.5rem; }
            .sev-critical { border-left: 4px solid #f85149; }
            .sev-high { border-left: 4px solid #d29922; }
            .sev-medium { border-left: 4px solid #58a6ff; }
            .sev-low { border-left: 4px solid #8b949e; }
            pre { background: #0d1117; padding: 1rem; border-radius: 8px; overflow-x: auto; margin: 0.5rem 0; font-size: 0.85rem; }
            pre.fix { border-left: 3px solid #3fb950; }
            footer { text-align: center; margin-top: 3rem; color: #8b949e; }
            h2 { margin: 2rem 0 1rem; color: #c9d1d9; }
            """;
    }
}
